name: MdEditor

on:
  pull_request:
    branches: 
      - develop

jobs:
  build:
    name: Build MdEditor
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: Build
        run: exec ./.github/build.sh