name: MdEditor UI Test

on:
  push:
    branches: 
      - develop

jobs:
  build:
    name: MdEditor UI Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: Testing
        run: exec ./.github/MdEditorUITest.sh