name: MdEditor

on:
  push:
    branches: 
      - develop

jobs:
  build:
    name: Build MdEditor
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      # - name: Mise Install
      #   run: |
      #     curl https://mise.jdx.dev/install.sh | sh
      #     echo "$HOME/.local/bin/mise" >> $GITHUB_PATH
      #     echo "eval \"\$(/Users/runner/.local/bin/mise activate bash)\"" >> ~/.bashrc
      #     reset
      - uses: jdx/mise-action@v2
      - name: Build
        run: exec ./.github/build.sh